-- =====================================================
-- Supabase Keepalive — dedicated keepalive objects
-- =====================================================
-- Safe to run: this script ONLY creates/updates:
--   1. table    public.cf_keep_alive        (dummy table)
--   2. function public.cf_keepalive_ping()  (touches only that table)
-- It does NOT modify any existing tables, data, or policies.
--
-- Run this once per Supabase project (SQL Editor → Run).
--
-- IMPORTANT:
-- Replace YOUR_KEEPALIVE_SECRET below with your own secret,
-- and use the SAME value in the Cloudflare Worker
-- (secret/variable: KEEPALIVE_SECRET).
-- =====================================================

-- 1) Dedicated dummy table
create table if not exists public.cf_keep_alive (
  id bigint generated by default as identity primary key,
  note text,
  created_at timestamztz not null default now()
);

-- Enable RLS. Direct table access is not used by the Worker;
-- all writes happen through the function below.
alter table public.cf_keep_alive enable row level security;
alter table public.cf_keep_alive no force row level security;

-- 2) Dedicated keepalive function (read + delete + insert)
drop function if exists public.cf_keepalive_ping(text);

create function public.cf_keepalive_ping(secret text)
returns json
language plpgsql
security definer
set search_path = public
as $$
declare
  -- MUST match the Worker's KEEPALIVE_SECRET
  expected_secret text := 'YOUR_KEEPALIVE_SECRET';

  existing_count bigint;
  deleted_count bigint;
  new_id bigint;
  random_note text;
begin
  -- Reject wrong secret
  if secret is distinct from expected_secret then
    raise exception 'invalid keepalive secret';
  end if;

  -- READ: how many dummy rows exist
  select count(*) into existing_count
  from public.cf_keep_alive;

  -- DELETE: clean dummy rows
  -- (WHERE clause required by Supabase safety rules;
  --  created_at <= now() is always true for existing rows)
  delete from public.cf_keep_alive
  where created_at <= now();

  get diagnostics deleted_count = row_count;

  -- INSERT: one random dummy row
  random_note :=
    'keepalive ' ||
    to_char(now(), 'YYYY-MM-DD HH24:MI:SS TZ') ||
    ' ' ||
    substr(md5(random()::text || clock_timestamp()::text), 1, 12);

  insert into public.cf_keep_alive (note)
  values (random_note)
  returning id into new_id;

  return json_build_object(
    'ok', true,
    'existing_count_before', existing_count,
    'deleted_rows', deleted_count,
    'inserted_id', new_id,
    'note', random_note,
    'at', now()
  );
end;
$$;

-- 3) Lock down execution: only the anon role (used by the Worker)
revoke all on function public.cf_keepalive_ping(text) from public;
grant execute on function public.cf_keepalive_ping(text) to anon;

comment on function public.cf_keepalive_ping(text) is
  'Dedicated keepalive function for the Cloudflare Worker. Only touches public.cf_keep_alive.';

-- =====================================================
-- OPTIONAL TEST (uncomment after replacing the secret):
-- select public.cf_keepalive_ping('YOUR_KEEPALIVE_SECRET');
-- =====================================================
